# --- Main Colors ---
background            #141311
foreground            #e6e2dd
cursor                #e6e2dd
cursor_text_color     #141311

selection_background  #49473a
selection_foreground  #e7e3d0

url_color             #cdc8a3

# --- ANSI Colors ---
color0                #141311
color1                #ffb4ab
color2                #cdc8a3
color3                #cbc7b5
color4                #ccc7ac
color5                #cdc8a3
color6                #cbc7b5
color7                #e6e2dd

color8                #484743
color9                #93000a
color10               #4a482c
color11               #49473a
color12               #4a4733
color13               #49473a
color14               #4a482c
color15               #c9c6c2

# --- Starship Prompt Bubbles ---
color255              #4a4733
color254              #ccc7ac
color253              #49473a
color252              #cbc7b5
color251              #4a482c
color250              #cdc8a3
color249              #93000a
color248              #ffb4ab

color232              #e8e3c7
color233              #33311e
color234              #e7e3d0
color235              #323124
color236              #e9e4be
color237              #333117
color238              #ffdad6
color239              #690005
color240              #e8e3c7

# Matched with unthemed light/dark
color243              #ccc7ac
color244              #ffb4ab
color245              #484743

# --- UI Elements ---
active_tab_foreground   #33311e
active_tab_background   #ccc7ac
inactive_tab_foreground #e8e3c7
inactive_tab_background #4a4733

active_border_color     #ccc7ac
inactive_border_color   #93908c

# --- Marks ---
mark1_foreground        #1e1c0b
mark1_background        #e8e3c7
mark2_foreground        #1d1c11
mark2_background        #e7e3d0
mark3_foreground        #1e1c05
mark3_background        #e9e4be