-- Generated by HyprMod

-- Settings
hl.config({
    misc = {
        disable_splash_rendering = true,
        vrr = 1,
    },
})

-- Monitors
hl.monitor({
    output = "DP-1",
    disabled = false,
    bitdepth = 10,
    mode = "2560x1440@180.00Hz",
    position = "0x0",
    scale = 1,
    cm = "auto",
    supports_hdr = 1,
    sdrbrightness = 0.5,
    sdr_min_luminance = 0,
    sdr_max_luminance = 400,
    min_luminance = 0,
    max_luminance = 400,
    max_avg_luminance = 400,
})
hl.monitor({
    output = "DP-2",
    disabled = false,
    bitdepth = 10,
    mode = "2560x1440@180.00Hz",
    position = "2560x0",
    scale = 1,
    cm = "auto",
    supports_hdr = 1,
    sdrbrightness = 0.5,
    sdr_min_luminance = 0,
    sdr_max_luminance = 400,
    min_luminance = 0,
    max_luminance = 400,
    max_avg_luminance = 400,
})
