# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e6e2dd"

# Title color for boxes
theme[title]="#ccc7ac"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#cbc7b5"

# Background color of selected item in processes box
theme[selected_bg]="#ccc7ac"

# Foreground color of selected item in processes box
theme[selected_fg]="#33311e"

# Color of inactive/disabled text
theme[inactive_fg]="#c9c6c2"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#cdc8a3"

# Cpu box outline color
theme[cpu_box]="#93908c"

# Memory/disks box outline color
theme[mem_box]="#93908c"

# Net up/down box outline color
theme[net_box]="#93908c"

# Processes box outline color
theme[proc_box]="#93908c"

# Box divider line and small boxes line color
theme[div_line]="#484743"

# Temperature graph colors
theme[temp_start]="#cbc7b5"
theme[temp_mid]="#ccc7ac"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#cbc7b5"
theme[cpu_mid]="#ccc7ac"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#cbc7b5"
theme[free_mid]=""
theme[free_end]="#49473a"

# Mem/Disk cached meter
theme[cached_start]="#cdc8a3"
theme[cached_mid]=""
theme[cached_end]="#4a482c"

# Mem/Disk available meter
theme[available_start]="#ccc7ac"
theme[available_mid]=""
theme[available_end]="#4a4733"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#cbc7b5"
theme[download_mid]="#ccc7ac"
theme[download_end]="#cdc8a3"

# Upload graph colors
theme[upload_start]="#cbc7b5"
theme[upload_mid]="#ccc7ac"
theme[upload_end]="#cdc8a3"